label: Products
icon: icon-asset-pool
appClass: info.magnolia.ui.contentapp.ContentApp
class: info.magnolia.ui.api.app.registry.ConfiguredAppDescriptor
subApps:
  browser:
    label: Products
    subAppClass: info.magnolia.ui.contentapp.browser.BrowserSubApp
    class: info.magnolia.ui.contentapp.browser.BrowserSubAppDescriptor
    contentConnector:
      includeProperties: false
      workspace: product-information
      rootPath: /
      defaultOrder: jcrName
      nodeTypes:
        - icon: icon-node-content
          name: product-information
          strict: true
        - icon: icon-tag-2
          strict: true
          name: mgnl:folder
    imageProvider:
      originalImageNodeName: photo
      imageProviderClass: info.magnolia.ui.imageprovider.DefaultImageProvider
      class: info.magnolia.ui.imageprovider.definition.ConfiguredImageProviderDefinition
    workbench:
      dropConstraintClass: info.magnolia.ui.workbench.tree.drop.AlwaysTrueDropConstraint
      editable: true
      contentViews:
        - name: tree
          class: info.magnolia.ui.workbench.tree.TreePresenterDefinition
          columns:
            - name: name
              label: Product Name
              sortable: true
              propertyName: name
              class: info.magnolia.ui.workbench.column.definition.PropertyColumnDefinition
            - name: status
              label: Status
              width: 100
              sortable: true
              displayInChooseDialog: false
              formatterClass: info.magnolia.ui.workbench.column.StatusColumnFormatter
              class: info.magnolia.ui.workbench.column.definition.StatusColumnDefinition
            - name: moddate
              label: Modification date
              width: 160
              sortable: true
              displayInChooseDialog: false
              formatterClass: info.magnolia.ui.workbench.column.DateColumnFormatter
              propertyName: mgnl:lastModified
              class: info.magnolia.ui.workbench.column.definition.MetaDataColumnDefinition
        - name: list
          class: info.magnolia.ui.workbench.list.ListPresenterDefinition
          columns:
            - name: name
              label: Product Name
              sortable: true
              propertyName: name
              class: info.magnolia.ui.workbench.column.definition.PropertyColumnDefinition
        - name: thumbnail
          class: info.magnolia.ui.workbench.thumbnail.ThumbnailPresenterDefinition
        - name: search
          class: info.magnolia.ui.workbench.search.SearchPresenterDefinition
          columns:
            - name: name
              label: Product Name
              sortable: true
              propertyName: name
              class: info.magnolia.ui.workbench.column.definition.PropertyColumnDefinition
    actions:
      editProduct-information:
        subAppId: detail
        label: Edit Product Details
        icon: icon-edit
        appName: product-information
        class: info.magnolia.ui.contentapp.detail.action.EditItemActionDefinition
        availability:
          writePermissionRequired: true
          nodeTypes:
            product-information: product-information
          rules:
            - name: IsNotDeletedRule
              implementationClass: info.magnolia.ui.framework.availability.IsNotDeletedRule
      create-page-from-product:
        icon: icon-add-item
        dialogName: product-information-app:pages/createCustomPage
        label: Create Page from Product
        class: io.cimpress.abc.product.app.pages.action.CreatePageFromProductDialogActionDefinition
        nodeType: mgnl:page
        availability:
          writePermissionRequired: true
          nodeTypes:
            product-information: product-information
          rules:
            - name: IsNotDeletedRule
              implementationClass: info.magnolia.ui.framework.availability.IsNotDeletedRule
      activate:
        command: activate
        icon: icon-publish
        catalog: versioned
        class: info.magnolia.ui.framework.action.ActivationActionDefinition
        availability:
          writePermissionRequired: true
      activateRecursive:
        catalog: versioned
        command: activate
        icon: icon-publish-incl-sub
        recursive: true
        class: info.magnolia.ui.framework.action.ActivationActionDefinition
        availability:
          writePermissionRequired: true
          rules:
            - name: IsNotDeletedRule
              implementationClass: info.magnolia.ui.framework.availability.IsNotDeletedRule
      deactivate:
        catalog: versioned
        command: deactivate
        icon: icon-unpublish
        class: info.magnolia.ui.framework.action.ActivationActionDefinition
        availability:
          writePermissionRequired: true
          rules:
            - name: IsNotDeletedRule
              implementationClass: info.magnolia.ui.framework.availability.IsNotDeletedRule
      export:
        command: export
        icon: icon-export
        class: info.magnolia.ui.framework.action.ExportActionDefinition
        availability:
          rules:
            - name: IsNotDeletedRule
              implementationClass: info.magnolia.ui.framework.availability.IsNotDeletedRule
      import:
        icon: icon-import
        dialogName: ui-admincentral:import
        class: info.magnolia.ui.framework.action.OpenCreateDialogActionDefinition
        availability:
          writePermissionRequired: true
          root: true
          rules:
            - name: IsNotDeletedRule
              implementationClass: info.magnolia.ui.framework.availability.IsNotDeletedRule
    actionbar:
      sections:
        - name: root
          label: Product Actions
          availability:
            nodes: false
            root: true
          groups:
            - name: createProduct
              items:
                - name: create-page-from-product
            - name: editActions
              items:
                - name: editProduct-information
            - name: publishingActions
              items:
                - name: activate
                - name: activateRecursive
                - name: deactivate
            - name: eximActions
              items:
                - name: export
                - name: import
        - name: product-information
          label: Product Actions
          availability:
            nodeTypes:
              product-information: product-information
          groups:
            - name: createProduct
              items:
                - name: create-page-from-product
            - name: editActions
              items:
                - name: editProduct-information
            - name: publishingActions
              items:
                - name: activate
                - name: activateRecursive
                - name: deactivate
            - name: eximActions
              items:
                - name: export
                - name: import
  detail:
    label: Product Information
    subAppClass: info.magnolia.ui.contentapp.detail.DetailSubApp
    class: info.magnolia.ui.contentapp.detail.DetailSubAppDescriptor
    contentConnector:
      defaultOrder: jcrName
      includeProperties: false
      rootPath: /
      workspace: product-information
      nodeTypes:
        - icon: icon-node-content
          name: product-information
          strict: true
    editor:
      workspace: product-information
      nodeType:
        icon: icon-items
        name: product-information
      form:
        tabs:
          - name: tabMain
            fields:
              - name: name
                class: info.magnolia.ui.form.field.definition.TextFieldDefinition
                readOnly: true
              - name: displayName
                class: info.magnolia.ui.form.field.definition.TextFieldDefinition
              - name: customDesc
                class: info.magnolia.ui.form.field.definition.RichTextFieldDefinition
                tables: true
                i18n: true
      actions:
        - name: commit
        - name: cancel
    actions:
      commit:
        implementationClass: info.magnolia.ui.form.action.SaveFormAction
        class: info.magnolia.ui.form.action.SaveFormActionDefinition
      cancel:
        class: info.magnolia.ui.form.action.CancelFormActionDefinition