title: product
templateScript: /product/templates/pages/product.ftl
renderType: freemarker
dialog: product:pages/product
visible: true
areas:
  topbar:
    availableComponents:
      topbar:
        id: home:components/topbar
  navbar:
    availableComponents:
      navbar:
        id: home:components/navbar
  footer:
    availableComponents:
      footer:
        id: home:components/footer
  copyright:
    availableComponents:
      copyright:
        id: home:components/copyright